import {
  pgTable,
  text,
  integer,
  jsonb,
  timestamp,
} from "drizzle-orm/pg-core";

// Tables mirror lib/types.ts. IDs are human-readable strings (WF-0001, DS-0001, ST-0001).
// Dates are stored as ISO date strings (text) to match the app's existing model.

export const opportunities = pgTable("opportunities", {
  id: text("id").primaryKey(),
  submittedDate: text("submitted_date").notNull().default(""),
  submittedBy: text("submitted_by").notNull().default(""),
  team: text("team").notNull().default(""),
  workflowName: text("workflow_name").notNull().default(""),
  workflowOwner: text("workflow_owner").notNull().default(""),
  peopleInvolved: text("people_involved").notNull().default(""),
  whoUsesOutput: text("who_uses_output").notNull().default(""),
  purpose: text("purpose").notNull().default(""),
  decisionSupported: text("decision_supported").notNull().default(""),
  whatHappensIfLate: text("what_happens_if_late").notNull().default(""),
  currentProcess: text("current_process").notNull().default(""),
  frequency: text("frequency").notNull().default("Unknown"),
  minutesPerRun: integer("minutes_per_run").notNull().default(0),
  peopleDoingWork: integer("people_doing_work").notNull().default(1),
  outputsPerCycle: text("outputs_per_cycle").notNull().default(""),
  systemsInvolved: text("systems_involved").notNull().default(""),
  numberOfSystems: integer("number_of_systems").notNull().default(0),
  frictionTypes: jsonb("friction_types").$type<string[]>().notNull().default([]),
  painRating: integer("pain_rating").notNull().default(3),
  businessCriticality: integer("business_criticality").notNull().default(3),
  errorProneness: integer("error_proneness").notNull().default(3),
  urgency: integer("urgency").notNull().default(3),
  peopleAffected: integer("people_affected").notNull().default(0),
  customersAffected: text("customers_affected").notNull().default(""),
  desiredFutureState: text("desired_future_state").notNull().default(""),
  humanReview: text("human_review").notNull().default(""),
  neverAutomate: text("never_automate").notNull().default(""),
  trust: text("trust").notNull().default(""),
  unusable: text("unusable").notNull().default(""),
  howWouldWeKnow: text("how_would_we_know").notNull().default(""),
  sensitiveData: text("sensitive_data").notNull().default("Unsure"),
  dataTypes: text("data_types").notNull().default(""),
  inputDataLocation: text("input_data_location").notNull().default(""),
  outputDestination: text("output_destination").notNull().default(""),
  existingReports: text("existing_reports").notNull().default(""),
  exampleLink: text("example_link").notNull().default(""),
  availableForWalkthrough: text("available_for_walkthrough").notNull().default("Maybe"),
  prototypeWillingness: text("prototype_willingness").notNull().default("Maybe"),
  idealTimeline: text("ideal_timeline").notNull().default(""),
  initialNotes: text("initial_notes").notNull().default(""),
  // Manual triage fields
  status: text("status").notNull().default("New"),
  likelySolutionType: text("likely_solution_type").notNull().default(""),
  feasibility: text("feasibility").notNull().default("Unknown"),
  riskLevel: text("risk_level").notNull().default("Unknown"),
  assignee: text("assignee").notNull().default(""),
  nextReviewDate: text("next_review_date").notNull().default(""),
  triageNotes: text("triage_notes").notNull().default(""),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});

export const discoverySessions = pgTable("discovery_sessions", {
  id: text("id").primaryKey(),
  opportunityId: text("opportunity_id").notNull().default(""),
  sessionDate: text("session_date").notNull().default(""),
  facilitator: text("facilitator").notNull().default(""),
  workflowOwnerSme: text("workflow_owner_sme").notNull().default(""),
  sessionType: text("session_type").notNull().default("Live Workflow Walkthrough"),
  sessionGoal: text("session_goal").notNull().default(""),
  summaryLearned: text("summary_learned").notNull().default(""),
  keyPainPoints: text("key_pain_points").notNull().default(""),
  risksGuardrails: text("risks_guardrails").notNull().default(""),
  dependencies: text("dependencies").notNull().default(""),
  likelySolutionDirection: text("likely_solution_direction").notNull().default(""),
  recommendedNextStep: text("recommended_next_step").notNull().default(""),
  ownerOfNextStep: text("owner_of_next_step").notNull().default(""),
  nextReviewDate: text("next_review_date").notNull().default(""),
  notes: text("notes").notNull().default(""),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});

export const discoverySteps = pgTable("discovery_steps", {
  id: text("id").primaryKey(),
  opportunityId: text("opportunity_id").notNull().default(""),
  sessionId: text("session_id").notNull().default(""),
  stepNumber: integer("step_number").notNull().default(1),
  stepDescription: text("step_description").notNull().default(""),
  toolSystem: text("tool_system").notNull().default(""),
  input: text("input").notNull().default(""),
  output: text("output").notNull().default(""),
  manualAction: text("manual_action").notNull().default(""),
  timeSpent: text("time_spent").notNull().default(""),
  painObserved: text("pain_observed").notNull().default(""),
  errorRiskPoint: text("error_risk_point").notNull().default(""),
  humanJudgment: text("human_judgment").notNull().default("Unknown"),
  couldBeAutomated: text("could_be_automated").notNull().default("Unknown"),
  couldBeAiAssisted: text("could_be_ai_assisted").notNull().default("Unknown"),
  dependency: text("dependency").notNull().default(""),
  notes: text("notes").notNull().default(""),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});
