CREATE TABLE "discovery_sessions" (
	"id" text PRIMARY KEY NOT NULL,
	"opportunity_id" text DEFAULT '' NOT NULL,
	"session_date" text DEFAULT '' NOT NULL,
	"facilitator" text DEFAULT '' NOT NULL,
	"workflow_owner_sme" text DEFAULT '' NOT NULL,
	"session_type" text DEFAULT 'Live Workflow Walkthrough' NOT NULL,
	"session_goal" text DEFAULT '' NOT NULL,
	"summary_learned" text DEFAULT '' NOT NULL,
	"key_pain_points" text DEFAULT '' NOT NULL,
	"risks_guardrails" text DEFAULT '' NOT NULL,
	"dependencies" text DEFAULT '' NOT NULL,
	"likely_solution_direction" text DEFAULT '' NOT NULL,
	"recommended_next_step" text DEFAULT '' NOT NULL,
	"owner_of_next_step" text DEFAULT '' NOT NULL,
	"next_review_date" text DEFAULT '' NOT NULL,
	"notes" text DEFAULT '' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "discovery_steps" (
	"id" text PRIMARY KEY NOT NULL,
	"opportunity_id" text DEFAULT '' NOT NULL,
	"session_id" text DEFAULT '' NOT NULL,
	"step_number" integer DEFAULT 1 NOT NULL,
	"step_description" text DEFAULT '' NOT NULL,
	"tool_system" text DEFAULT '' NOT NULL,
	"input" text DEFAULT '' NOT NULL,
	"output" text DEFAULT '' NOT NULL,
	"manual_action" text DEFAULT '' NOT NULL,
	"time_spent" text DEFAULT '' NOT NULL,
	"pain_observed" text DEFAULT '' NOT NULL,
	"error_risk_point" text DEFAULT '' NOT NULL,
	"human_judgment" text DEFAULT 'Unknown' NOT NULL,
	"could_be_automated" text DEFAULT 'Unknown' NOT NULL,
	"could_be_ai_assisted" text DEFAULT 'Unknown' NOT NULL,
	"dependency" text DEFAULT '' NOT NULL,
	"notes" text DEFAULT '' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "opportunities" (
	"id" text PRIMARY KEY NOT NULL,
	"submitted_date" text DEFAULT '' NOT NULL,
	"submitted_by" text DEFAULT '' NOT NULL,
	"team" text DEFAULT '' NOT NULL,
	"workflow_name" text DEFAULT '' NOT NULL,
	"workflow_owner" text DEFAULT '' NOT NULL,
	"people_involved" text DEFAULT '' NOT NULL,
	"who_uses_output" text DEFAULT '' NOT NULL,
	"purpose" text DEFAULT '' NOT NULL,
	"decision_supported" text DEFAULT '' NOT NULL,
	"what_happens_if_late" text DEFAULT '' NOT NULL,
	"current_process" text DEFAULT '' NOT NULL,
	"frequency" text DEFAULT 'Unknown' NOT NULL,
	"minutes_per_run" integer DEFAULT 0 NOT NULL,
	"people_doing_work" integer DEFAULT 1 NOT NULL,
	"outputs_per_cycle" text DEFAULT '' NOT NULL,
	"systems_involved" text DEFAULT '' NOT NULL,
	"number_of_systems" integer DEFAULT 0 NOT NULL,
	"friction_types" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"pain_rating" integer DEFAULT 3 NOT NULL,
	"business_criticality" integer DEFAULT 3 NOT NULL,
	"error_proneness" integer DEFAULT 3 NOT NULL,
	"urgency" integer DEFAULT 3 NOT NULL,
	"people_affected" integer DEFAULT 0 NOT NULL,
	"customers_affected" text DEFAULT '' NOT NULL,
	"desired_future_state" text DEFAULT '' NOT NULL,
	"human_review" text DEFAULT '' NOT NULL,
	"never_automate" text DEFAULT '' NOT NULL,
	"trust" text DEFAULT '' NOT NULL,
	"unusable" text DEFAULT '' NOT NULL,
	"how_would_we_know" text DEFAULT '' NOT NULL,
	"sensitive_data" text DEFAULT 'Unsure' NOT NULL,
	"data_types" text DEFAULT '' NOT NULL,
	"input_data_location" text DEFAULT '' NOT NULL,
	"output_destination" text DEFAULT '' NOT NULL,
	"existing_reports" text DEFAULT '' NOT NULL,
	"example_link" text DEFAULT '' NOT NULL,
	"available_for_walkthrough" text DEFAULT 'Maybe' NOT NULL,
	"prototype_willingness" text DEFAULT 'Maybe' NOT NULL,
	"ideal_timeline" text DEFAULT '' NOT NULL,
	"initial_notes" text DEFAULT '' NOT NULL,
	"status" text DEFAULT 'New' NOT NULL,
	"likely_solution_type" text DEFAULT '' NOT NULL,
	"feasibility" text DEFAULT 'Unknown' NOT NULL,
	"risk_level" text DEFAULT 'Unknown' NOT NULL,
	"assignee" text DEFAULT '' NOT NULL,
	"next_review_date" text DEFAULT '' NOT NULL,
	"triage_notes" text DEFAULT '' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now()
);
