import type { Opportunity, DiscoverySession, DiscoveryStep } from "./types";

// A few realistic seed opportunities so the UI feels alive before the DB exists.
export const SEED_OPPORTUNITIES: Opportunity[] = [
  {
    id: "WF-0001",
    submittedDate: "2026-06-10",
    submittedBy: "Dana Whitfield",
    team: "Customer Support",
    workflowName: "Weekly escalation summary for district admins",
    workflowOwner: "Dana Whitfield",
    peopleInvolved: "3 support leads",
    whoUsesOutput: "District admins, CS managers",
    purpose:
      "Give district admins a digest of unresolved escalations so they can intervene before renewal conversations.",
    decisionSupported: "Whether to escalate to CS or engineering",
    whatHappensIfLate:
      "Admins lose visibility, escalations age, renewal risk increases.",
    currentProcess:
      "Pull tickets from Zendesk, copy into a sheet, manually categorize, write a summary paragraph per district, paste into email.",
    frequency: "Weekly",
    minutesPerRun: 90,
    peopleDoingWork: 3,
    outputsPerCycle: "~12 district summaries",
    systemsInvolved: "Zendesk, Google Sheets, Gmail",
    numberOfSystems: 3,
    frictionTypes: [
      "Multi-system data gathering",
      "Summarizing or synthesizing information",
      "Manual reporting",
    ],
    painRating: 4,
    businessCriticality: 4,
    errorProneness: 3,
    urgency: 4,
    peopleAffected: 12,
    customersAffected: "~40 districts",
    desiredFutureState:
      "Draft summaries generated automatically from Zendesk, reviewed by a lead before send.",
    humanReview: "Final wording and tone before sending to admins.",
    neverAutomate: "Deciding which escalations are renewal-threatening.",
    trust: "Citations back to ticket IDs and an editable draft.",
    unusable: "If it invented ticket details or misattributed districts.",
    howWouldWeKnow: "Summary prep time drops below 20 min; admin replies stay flat or improve.",
    sensitiveData: "Yes",
    dataTypes: "Customer support tickets, district names",
    inputDataLocation: "Zendesk",
    outputDestination: "Gmail / district admin inboxes",
    existingReports: "Yes — the weekly sheet template",
    exampleLink: "",
    availableForWalkthrough: "Yes",
    prototypeWillingness: "Yes",
    idealTimeline: "This month",
    initialNotes: "High-frequency, clear template. Strong summarization candidate.",
    status: "Needs Discovery",
    likelySolutionType: "AI-assisted summarization",
    feasibility: "Medium",
    riskLevel: "Medium",
    assignee: "Tom Leger",
    nextReviewDate: "2026-07-01",
    triageNotes: "Confirm Zendesk API access during discovery.",
  },
  {
    id: "WF-0002",
    submittedDate: "2026-06-12",
    submittedBy: "Marcus Lee",
    team: "Finance",
    workflowName: "Monthly vendor invoice reconciliation",
    workflowOwner: "Priya Nair",
    peopleInvolved: "2 finance analysts",
    whoUsesOutput: "Controller, AP team",
    purpose: "Match vendor invoices to POs and flag discrepancies before payment.",
    decisionSupported: "Approve or hold vendor payment",
    whatHappensIfLate: "Late payments, missed early-pay discounts, vendor friction.",
    currentProcess:
      "Download invoices from email, open NetSuite, match line by line, flag mismatches in a sheet, email AP.",
    frequency: "Monthly",
    minutesPerRun: 240,
    peopleDoingWork: 2,
    outputsPerCycle: "~150 invoices",
    systemsInvolved: "Gmail, NetSuite, Excel",
    numberOfSystems: 3,
    frictionTypes: [
      "Multi-system data gathering",
      "Data cleanup or normalization",
      "Manual QA/checking",
      "Error-prone process",
    ],
    painRating: 5,
    businessCriticality: 5,
    errorProneness: 4,
    urgency: 3,
    peopleAffected: 6,
    customersAffected: "",
    desiredFutureState: "Auto-matched invoices with only exceptions surfaced for review.",
    humanReview: "Approval of any flagged discrepancy over $1,000.",
    neverAutomate: "Final payment authorization.",
    trust: "Clear audit trail and a confidence score per match.",
    unusable: "If it auto-approved payments without a human gate.",
    howWouldWeKnow: "Reconciliation time halved; discrepancy catch rate improves.",
    sensitiveData: "Yes",
    dataTypes: "Financial records, vendor banking details",
    inputDataLocation: "NetSuite, email",
    outputDestination: "NetSuite, AP workflow",
    existingReports: "Yes — reconciliation workbook",
    exampleLink: "",
    availableForWalkthrough: "Yes",
    prototypeWillingness: "Maybe",
    idealTimeline: "This quarter",
    initialNotes: "High value but financial data — needs risk review.",
    status: "New",
    likelySolutionType: "Workflow automation",
    feasibility: "Hard",
    riskLevel: "High",
    assignee: "",
    nextReviewDate: "",
    triageNotes: "",
  },
  {
    id: "WF-0003",
    submittedDate: "2026-06-18",
    submittedBy: "Sofia Reyes",
    team: "Marketing",
    workflowName: "Repurposing webinar transcripts into blog drafts",
    workflowOwner: "Sofia Reyes",
    peopleInvolved: "1 content marketer",
    whoUsesOutput: "Marketing, demand gen",
    purpose: "Turn webinar recordings into blog content to extend reach.",
    decisionSupported: "What content ships to the blog calendar",
    whatHappensIfLate: "Content backlog grows; webinar value decays quickly.",
    currentProcess:
      "Export transcript, read through, pull quotes, write a 600-word draft, format in the CMS.",
    frequency: "Weekly",
    minutesPerRun: 120,
    peopleDoingWork: 1,
    outputsPerCycle: "1-2 drafts",
    systemsInvolved: "Zoom, Google Docs, WordPress",
    numberOfSystems: 3,
    frictionTypes: ["Writing or rewriting", "Summarizing or synthesizing information"],
    painRating: 3,
    businessCriticality: 2,
    errorProneness: 2,
    urgency: 2,
    peopleAffected: 2,
    customersAffected: "",
    desiredFutureState: "First-draft blog post generated from transcript, human-polished.",
    humanReview: "Brand voice, accuracy of claims, final edit.",
    neverAutomate: "Publishing without human approval.",
    trust: "Draft stays close to the transcript; no fabricated stats.",
    unusable: "If drafts needed more editing than writing from scratch.",
    howWouldWeKnow: "Draft-to-publish time drops; more webinars get repurposed.",
    sensitiveData: "No",
    dataTypes: "Public webinar content",
    inputDataLocation: "Zoom cloud recordings",
    outputDestination: "WordPress drafts",
    existingReports: "No",
    exampleLink: "",
    availableForWalkthrough: "Maybe",
    prototypeWillingness: "Yes",
    idealTimeline: "This week",
    initialNotes: "Low risk, fast win for content team.",
    status: "Discovery Complete",
    likelySolutionType: "AI-assisted writing",
    feasibility: "Easy",
    riskLevel: "Low",
    assignee: "Tom Leger",
    nextReviewDate: "2026-06-28",
    triageNotes: "Clear quick win. Public data, willing owner.",
  },
];

export const SEED_SESSIONS: DiscoverySession[] = [
  {
    id: "DS-0001",
    opportunityId: "WF-0003",
    sessionDate: "2026-06-20",
    facilitator: "Tom Leger",
    workflowOwnerSme: "Sofia Reyes",
    sessionType: "Live Workflow Walkthrough",
    sessionGoal: "Watch the transcript-to-draft process end to end.",
    summaryLearned:
      "Most time goes to reading the transcript and pulling quotes; formatting in WordPress is quick. Strong fit for AI drafting with human edit.",
    keyPainPoints: "Reading long transcripts; finding the best quotes.",
    risksGuardrails: "Avoid fabricated statistics; keep brand voice.",
    dependencies: "Zoom transcript export access; WordPress draft permissions.",
    likelySolutionDirection: "AI-assisted writing",
    recommendedNextStep: "Build a prototype drafting prompt against 3 past transcripts.",
    ownerOfNextStep: "Tom Leger",
    nextReviewDate: "2026-06-28",
    notes: "Sofia is an enthusiastic early adopter.",
  },
  {
    id: "DS-0002",
    opportunityId: "WF-0001",
    sessionDate: "2026-06-22",
    facilitator: "Tom Leger",
    workflowOwnerSme: "Dana Whitfield",
    sessionType: "Stakeholder Interview",
    sessionGoal: "Understand how escalation severity is judged.",
    summaryLearned:
      "Severity judgment is nuanced and relationship-driven. Summarization can draft, but a lead must set tone and pick what to surface.",
    keyPainPoints: "Manual categorization; copying across three tools.",
    risksGuardrails: "Customer data; must keep human in the loop on tone.",
    dependencies: "Zendesk API; agreement on district grouping.",
    likelySolutionDirection: "AI-assisted summarization",
    recommendedNextStep: "Scope Zendesk read access and draft a summary template.",
    ownerOfNextStep: "Tom Leger",
    nextReviewDate: "2026-07-01",
    notes: "",
  },
];

export const SEED_STEPS: DiscoveryStep[] = [
  {
    id: "ST-0001",
    opportunityId: "WF-0003",
    sessionId: "DS-0001",
    stepNumber: 1,
    stepDescription: "Export transcript from Zoom cloud recording.",
    toolSystem: "Zoom",
    input: "Webinar recording",
    output: "Raw .vtt transcript",
    manualAction: "Download, open, clean timestamps",
    timeSpent: "10 min",
    painObserved: "Timestamps clutter the text.",
    errorRiskPoint: "Wrong recording selected.",
    humanJudgment: "No",
    couldBeAutomated: "Yes",
    couldBeAiAssisted: "No",
    dependency: "Zoom export permission",
    notes: "",
  },
  {
    id: "ST-0002",
    opportunityId: "WF-0003",
    sessionId: "DS-0001",
    stepNumber: 2,
    stepDescription: "Read transcript and highlight key quotes/themes.",
    toolSystem: "Google Docs",
    input: "Cleaned transcript",
    output: "Highlighted quotes",
    manualAction: "Read, highlight, summarize mentally",
    timeSpent: "45 min",
    painObserved: "Slowest, most tedious step.",
    errorRiskPoint: "Missing the best quote.",
    humanJudgment: "Sometimes",
    couldBeAutomated: "No",
    couldBeAiAssisted: "Yes",
    dependency: "",
    notes: "Prime AI assistance target.",
  },
  {
    id: "ST-0003",
    opportunityId: "WF-0003",
    sessionId: "DS-0001",
    stepNumber: 3,
    stepDescription: "Write 600-word blog draft.",
    toolSystem: "Google Docs",
    input: "Quotes + themes",
    output: "Blog draft",
    manualAction: "Write, edit for voice",
    timeSpent: "50 min",
    painObserved: "Blank-page friction.",
    errorRiskPoint: "Off-brand tone.",
    humanJudgment: "Yes",
    couldBeAutomated: "No",
    couldBeAiAssisted: "Yes",
    dependency: "",
    notes: "",
  },
];
